"""
Stage 5: Dockerfile 与 docker-compose 编排

学习目标：
1. 理解 Dockerfile 的基本指令（FROM, RUN, COPY, ENV, EXPOSE, HEALTHCHECK）
2. 学会基于 vLLM 官方镜像编写自定义 Dockerfile
3. 理解 Docker 层缓存与构建优化s    
4. 掌握 docker-compose 的核心概念和编写方法
5. 理解卷挂载策略和服务依赖编排

核心概念：
- Dockerfile：定义镜像构建步骤的文本文件
- HEALTHCHECK：容器健康检查，确保服务真正可用
- docker-compose：多服务编排工具，定义服务/网络/卷
- 服务依赖：depends_on + condition: service_healthy

前置条件：
- 理解 01_docker_basics.py 中的 Docker 基础概念
- Docker 和 nvidia-container-toolkit 已安装
"""

import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv(Path(__file__).resolve().parent.parent / ".env")

HF_HOME = os.environ.get("HF_HOME", "")


def explain_dockerfile_structure():
    """
    Dockerfile 指令详解
    """
    print("=" * 60)
    print("Dockerfile 指令详解")
    print("=" * 60)
    print()
    print("vLLM 自定义 Dockerfile 示例（见 docker/Dockerfile.vllm）：")
    print()
    print("```dockerfile")
    print("# 1. FROM — 基础镜像")
    print("FROM vllm/vllm-openai:v0.19.0")
    print("#  → 所有后续指令都基于此镜像构建")
    print("#  → 已包含 Python, vLLM, CUDA, 系统库")
    print()
    print("# 2. ENV — 设置环境变量")
    print('ENV HF_HOME=/root/.cache/huggingface \\')
    print('    PYTORCH_CUDA_ALLOC_CONF=expandable_segments:Max:640x64000')
    print("#  → 容器运行时这些变量可用")
    print("#  → PYTORCH_CUDA_ALLOC_CONF 减少显存碎片")
    print()
    print("# 3. HEALTHCHECK — 健康检查")
    print("HEALTHCHECK --interval=30s --timeout=10s --start-period=120s --retries=3 \\")
    print("    CMD curl -f http://localhost:8000/health || exit 1")
    print("#  → 每 30s 检查一次 /health 端点")
    print("#  → start-period=120s：模型加载需要 30-90s，给足启动时间")
    print("#  → 连续 3 次失败才标记为 unhealthy")
    print()
    print("# 4. EXPOSE — 声明端口（文档作用）")
    print("EXPOSE 8000")
    print("#  → 不实际发布端口，仅作为文档说明")
    print("#  → 实际端口映射在 docker run -p 或 compose 中配置")
    print()
    print("# 5. ENTRYPOINT — 默认启动命令")
    print('ENTRYPOINT ["python", "-m", "vllm.entrypoints.openai.api_server"]')
    print("#  → 容器启动时执行的命令")
    print("#  → 可被 docker-compose command 覆盖")
    print("```")
    print()


def explain_healthcheck():
    """
    HEALTHCHECK 对 LLM 服务的意义
    """
    print("=" * 60)
    print("HEALTHCHECK：LLM 服务的健康检查")
    print("=" * 60)
    print()
    print("为什么 HEALTHCHECK 对 LLM 部署特别重要？")
    print()
    print("  vLLM 启动流程：")
    print("  [启动进程] → [加载模型权重 30-90s] → [编译 CUDA Graph 10-30s] → [就绪]")
    print()
    print("  Docker 容器启动 ≠ 服务可用！")
    print("  容器状态 running，但 vLLM 可能还在加载模型")
    print()
    print("vLLM 的 /health 端点：")
    print("  - 模型加载中：返回 503 Service Unavailable")
    print("  - 模型就绪后：返回 200 OK")
    print()
    print("HEALTHCHECK 参数调优：")
    print()
    print("  --interval=30s")
    print("    每 30 秒检查一次，够用（LLM 状态不会秒级变化）")
    print()
    print("  --timeout=10s")
    print("    单次检查超时 10 秒")
    print("    vLLM 正常时 /health 响应 <100ms，10s 足够")
    print()
    print("  --start-period=120s")
    print("    ⚠️  关键参数！模型加载期间的检查不计入失败次数")
    print("    7B 模型加载约 30-60s，72B 可能 2-3 分钟")
    print("    设 120s 留有余量")
    print()
    print("  --retries=3")
    print("    连续 3 次失败才标记为 unhealthy")
    print("    避免偶发的网络抖动导致误判")
    print()
    print("在 docker-compose 中使用：")
    print("  depends_on:")
    print("    vllm:")
    print("      condition: service_healthy")
    print("  → Nginx/Prometheus 等 vLLm 就绪后才启动")
    print()


def explain_build_cache():
    """
    Docker 层缓存与构建优化
    """
    print("=" * 60)
    print("Docker 层缓存与构建优化")
    print("=" * 60)
    print()
    print("Docker 镜像由多层组成，每条指令创建一层：")
    print()
    print("  FROM vllm/vllm-openai:v0.19.0    → 层1: 基础镜像（~8GB）")
    print("  ENV HF_HOME=...                    → 层2: 环境变量（几字节）")
    print("  COPY requirements.txt .            → 层3: 依赖声明（几KB）")
    print("  RUN pip install -r requirements    → 层4: 安装依赖（可能很大）")
    print("  COPY . .                           → 层5: 源代码（几KB-MB）")
    print()
    print("缓存规则：")
    print("  - 某层变化 → 该层及后续所有层重新构建")
    print("  - 未变化的层 → 直接使用缓存，秒级完成")
    print()
    print("优化原则：变化少的指令放前面，变化多的放后面")
    print()
    print("  ❌ 差的顺序：")
    print("  COPY . .                    # 源码一变，后面的全重建")
    print("  RUN pip install -r req.txt  # 依赖没变也要重装！")
    print()
    print("  ✓ 好的顺序：")
    print("  COPY requirements.txt .     # 依赖声明单独复制")
    print("  RUN pip install -r req.txt  # 依赖不变就命中缓存")
    print("  COPY . .                    # 源码变化只重建最后一层")
    print()
    print("对 vLLM 部署的影响：")
    print("  - 直接用官方镜像 → 不需要构建，无缓存问题")
    print("  - 自定义镜像 → 注意层顺序，避免频繁重装依赖")
    print("  - 用 .dockerignore 排除不必要的文件（模型、__pycache__）")
    print()


def explain_compose_concepts():
    """
    docker-compose 核心概念
    """
    print("=" * 60)
    print("docker-compose 核心概念")
    print("=" * 60)
    print()
    print("为什么需要 docker-compose？")
    print("  - 一个 docker run 命令只能启动一个容器")
    print("  - 生产部署需要多个服务：vLLM + Nginx + Prometheus + Grafana")
    print("  - docker-compose 用一个 YAML 文件定义所有服务")
    print()
    print("服务拓扑：")
    print()
    print("  ┌──────────┐")
    print("  │  Client   │")
    print("  └────┬─────┘")
    print("       │ :80")
    print("  ┌────▼─────┐")
    print("  │  Nginx   │ ← 反向代理 + 限流")
    print("  └────┬─────┘")
    print("       │ :8000")
    print("  ┌────▼─────┐     ┌────────────┐")
    print("  │  vLLM    │────→│ Prometheus │ ← 抓取 /metrics")
    print("  └──────────┘     └─────┬──────┘")
    print("                         │")
    print("                   ┌─────▼──────┐")
    print("                   │  Grafana   │ ← 可视化面板")
    print("                   └────────────┘")
    print()
    print("compose 核心元素：")
    print()
    print("  services:      定义各个服务（容器）")
    print("  volumes:       定义持久化存储")
    print("  networks:      定义虚拟网络")
    print()
    print("服务间通信：")
    print("  - 同一网络内的服务可用服务名互访")
    print("  - 如 Nginx 配置 proxy_pass http://vllm:8000")
    print("  - 不需要知道对方的 IP 地址")
    print()


def explain_volume_strategy():
    """
    卷挂载策略
    """
    print("=" * 60)
    print("卷挂载策略")
    print("=" * 60)
    print()
    print("三种挂载方式，各有用途：")
    print()
    print("1. Bind Mount（绑定挂载）— 宿主机目录映射")
    print("   用途：模型缓存、配置文件")
    print()
    print(f"   -v {HF_HOME}:/root/.cache/huggingface:ro")
    print("        ↑ 宿主机路径              ↑ 容器路径      ↑ 只读")
    print()
    print("   为什么要 :ro（只读）？")
    print("   - 防止容器意外修改宿主机的模型缓存")
    print("   - 多个容器共享同一缓存时，避免并发写入冲突")
    print("   - 如果需要下载模型，在宿主机上操作，不在容器内")
    print()
    print("   -v ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro")
    print("   -v ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro")
    print("   配置文件也用 :ro，容器不应修改配置")
    print()
    print("2. Named Volume（命名卷）— Docker 管理的持久化存储")
    print("   用途：Prometheus 数据、Grafana 数据")
    print()
    print("   volumes:")
    print("     prometheus-data:      # 声明命名卷")
    print("     grafana-data:")
    print()
    print("   服务中使用：")
    print("   volumes:")
    print("     - prometheus-data:/prometheus    # 监控数据持久化")
    print("     - grafana-data:/var/lib/grafana  # 仪表盘配置持久化")
    print()
    print("   优势：")
    print("   - 容器删除后数据不丢失")
    print("   - Docker 自动管理存储位置")
    print("   - 不关心宿主机上的具体路径")
    print()
    print("3. tmpfs — 内存文件系统（临时，不常用）")
    print("   适合存放临时数据，容器停止即消失")
    print()


def explain_compose_walkthrough():
    """
    docker-compose.yml 逐字段解析
    """
    print("=" * 60)
    print("docker-compose.yml 逐字段解析")
    print("=" * 60)
    print()
    print("完整文件见 docker/docker-compose.yml，以下逐字段讲解：")
    print()
    print("--- vllm 服务 ---")
    print()
    print("services:")
    print("  vllm:")
    print("    build:")
    print("      context: .                      # 构建上下文目录")
    print("      dockerfile: Dockerfile.vllm     # 使用的 Dockerfile")
    print("    container_name: vllm-server        # 容器名称")
    print("    ports:")
    print("      - '8000:8000'                    # 宿主:容器 端口映射")
    print("    volumes:")
    print(f"      - '{HF_HOME}:/root/.cache/huggingface:ro'  # 模型缓存（只读）")
    print("    environment:")
    print("      - HF_HOME=/root/.cache/huggingface")
    print("    command:")
    print("      - --model=Qwen/Qwen2.5-7B-Instruct")
    print("      - --tensor-parallel-size=2")
    print("      - --gpu-memory-utilization=0.9")
    print("      - --max-model-len=4096")
    print("      - --dtype=bfloat16")
    print("    deploy:")
    print("      resources:")
    print("        reservations:")
    print("          devices:")
    print("            - driver: nvidia")
    print("              device_ids: ['0', '1']    # 使用 GPU 0 和 1")
    print("              capabilities: [gpu]")
    print("    ipc: host                           # 共享内存（TP 必需）")
    print("    healthcheck:")
    print("      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']")
    print("      interval: 30s")
    print("      timeout: 10s")
    print("      start_period: 120s                # 模型加载缓冲期")
    print("      retries: 3")
    print("    networks:")
    print("      - llm-deploy-net")
    print("    restart: unless-stopped             # 异常退出自动重启")
    print()
    print("--- nginx 服务 ---")
    print()
    print("  nginx:")
    print("    image: nginx:1.27-alpine             # 轻量 Nginx 镜像")
    print("    ports:")
    print("      - '80:80'")
    print("    volumes:")
    print("      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro")
    print("    depends_on:")
    print("      vllm:")
    print("        condition: service_healthy        # 等 vLLM 就绪再启动")
    print("    networks:")
    print("      - llm-deploy-net")
    print()
    print("--- prometheus 服务 ---")
    print()
    print("  prometheus:")
    print("    image: prom/prometheus:v2.55.0")
    print("    ports:")
    print("      - '9090:9090'")
    print("    volumes:")
    print("      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro")
    print("      - prometheus-data:/prometheus      # 命名卷持久化")
    print("    command:")
    print("      - '--config.file=/etc/prometheus/prometheus.yml'")
    print("      - '--storage.tsdb.retention.time=7d'  # 保留 7 天数据")
    print("    depends_on:")
    print("      vllm:")
    print("        condition: service_healthy")
    print()
    print("--- grafana 服务 ---")
    print()
    print("  grafana:")
    print("    image: grafana/grafana:11.4.0")
    print("    ports:")
    print("      - '3000:3000'")
    print("    environment:")
    print("      - GF_SECURITY_ADMIN_PASSWORD=admin")
    print("    volumes:")
    print("      - ./grafana/provisioning:/etc/grafana/provisioning:ro")
    print("      - grafana-data:/var/lib/grafana")
    print("    depends_on:")
    print("      - prometheus                       # 只需 prometheus 启动即可")
    print()
    print("--- 全局配置 ---")
    print()
    print("volumes:")
    print("  prometheus-data:                       # 声明命名卷")
    print("  grafana-data:")
    print()
    print("networks:")
    print("  llm-deploy-net:")
    print("    driver: bridge                       # 桥接网络")
    print()
    print("服务启动顺序（由 depends_on 控制）：")
    print("  vllm → (healthy) → nginx + prometheus → grafana")
    print()


def demo_compose_commands():
    """
    docker compose 常用命令
    """
    print("=" * 60)
    print("docker compose 常用命令")
    print("=" * 60)
    print()
    print("在 stage5-production/docker/ 目录下执行：")
    print()
    print("  # 启动所有服务（后台运行）")
    print("  docker compose up -d")
    print()
    print("  # 只启动 vLLM（调试用）")
    print("  docker compose up -d vllm")
    print()
    print("  # 查看服务状态")
    print("  docker compose ps")
    print()
    print("  # 查看某个服务的日志")
    print("  docker compose logs -f vllm")
    print("  docker compose logs --tail 50 nginx")
    print()
    print("  # 重启某个服务（保留其他服务）")
    print("  docker compose restart vllm")
    print()
    print("  # 停止并删除所有容器（保留数据卷）")
    print("  docker compose down")
    print()
    print("  # 停止并删除所有容器和数据卷（⚠️ 清空监控数据）")
    print("  docker compose down -v")
    print()
    print("  # 重新构建镜像（Dockerfile 变更后）")
    print("  docker compose build vllm")
    print()
    print("  # 更新某个服务（重建+重启，不影响其他服务）")
    print("  docker compose up -d --no-deps --build vllm")
    print()
    print("  # 在运行中的容器内执行命令")
    print("  docker compose exec vllm nvidia-smi")
    print("  docker compose exec vllm python -c 'import vllm; print(vllm.__version__)'")
    print()
    print("  # 查看资源使用")
    print("  docker compose top")
    print()


if __name__ == "__main__":
    print("大模型部署学习 - Stage 5: Dockerfile 与 docker-compose 编排")
    print()

    # 1. Dockerfile 讲解
    # explain_dockerfile_structure()
    # explain_healthcheck()
    # explain_build_cache()

    # # 2. docker-compose 讲解
    # explain_compose_concepts()
    # explain_volume_strategy()
    explain_compose_walkthrough()

    # 3. 常用命令
    demo_compose_commands()

    print("=" * 60)
    print("Stage 5 Dockerfile & Compose 要点总结")
    print("=" * 60)
    print("1. Dockerfile 基于 vllm/vllm-openai 官方镜像，添加 HEALTHCHECK 和 ENV")
    print("2. HEALTHCHECK 的 start-period 要给足模型加载时间（120s+）")
    print("3. 层缓存优化：变化少的指令放前面，变化多的放后面")
    print("4. docker-compose 编排多服务：vLLM + Nginx + Prometheus + Grafana")
    print("5. 模型缓存用 bind mount(:ro)，监控数据用 named volume")
    print("6. depends_on + condition: service_healthy 确保启动顺序正确")
