"""
Stage 5: 高级部署策略

学习目标：
1. 掌握多实例部署与请求路由策略
2. 理解模型预热（warmup）与冷启动优化
3. 学会实现限流与排队策略
4. 了解滚动更新与零停机部署
5. 掌握生产环境的安全加固

核心概念：
- 多实例部署：同一模型部署多个 vLLM 实例，Nginx 负载均衡
- GPU 绑定：每个 vLLM 实例绑定不同的 GPU，避免资源竞争
- 模型预热：启动后发送 warmup 请求，编译 CUDA Graph + 分配 KV Cache
- 冷启动：首次请求延迟高（模型加载 + CUDA Graph 编译）
- 滚动更新：逐个更新实例，保持服务可用
- 安全加固：最小权限、网络隔离、密钥管理

前置条件：
- 完成 01-04 脚本的学习
- 理解 docker-compose 和 Nginx 的基本配置

配置文件位置：
- docker/docker-compose.multi.yml（多实例部署）
"""

import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv(Path(__file__).resolve().parent.parent / ".env")

import json
import time
import requests

HF_HOME = os.environ.get("HF_HOME", "")


def explain_multi_instance():
    """
    多实例部署架构
    """
    print("=" * 60)
    print("多实例部署：GPU 资源的最大化利用")
    print("=" * 60)
    print()
    print("单实例的局限：")
    print("  - 7B 模型 TP=2 只用 2 张 GPU，另外 2 张闲置")
    print("  - 所有请求走一个实例，吞吐量有上限")
    print()
    print("方案A：同模型多实例（提升吞吐）")
    print()
    print("  ┌───────────────────────────────────────────────────┐")
    print("  │  Nginx (:80)                                       │")
    print("  │    least_conn 负载均衡                              │")
    print("  │      ├── vllm-1 (:8000) → GPU 0,1 (7B BF16)       │")
    print("  │      └── vllm-2 (:8001) → GPU 2,3 (7B BF16)       │")
    print("  └───────────────────────────────────────────────────┘")
    print()
    print("  优势：吞吐量翻倍，延迟不变")
    print("  适用：高并发场景，用户量大")
    print()
    print("方案B：异构模型部署（按需路由）")
    print()
    print("  ┌───────────────────────────────────────────────────┐")
    print("  │  Nginx (:80)                                       │")
    print("  │    按路径路由：                                     │")
    print("  │      /v1/chat/7b  → vllm-7b  (:8000) → GPU 0,1    │")
    print("  │      /v1/chat/32b → vllm-32b (:8001) → GPU 2,3    │")
    print("  └───────────────────────────────────────────────────┘")
    print()
    print("  优势：不同复杂度的请求用不同模型")
    print("  适用：简单问题用 7B（快），复杂推理用 32B（准）")
    print()
    print("docker-compose.multi.yml 配置要点：")
    print()
    print("  services:")
    print("    vllm-7b:")
    print("      deploy:")
    print("        resources:")
    print("          reservations:")
    print("            devices:")
    print("              - driver: nvidia")
    print("                device_ids: ['0', '1']    # 绑定 GPU 0,1")
    print("                capabilities: [gpu]")
    print("      command:")
    print("        - --model=Qwen/Qwen2.5-7B-Instruct")
    print("        - --tensor-parallel-size=2")
    print()
    print("    vllm-32b:")
    print("      deploy:")
    print("        resources:")
    print("          reservations:")
    print("            devices:")
    print("              - driver: nvidia")
    print("                device_ids: ['2', '3']    # 绑定 GPU 2,3")
    print("                capabilities: [gpu]")
    print("      command:")
    print("        - --model=Qwen/Qwen2.5-32B-Instruct-AWQ")
    print("        - --tensor-parallel-size=2")
    print("        - --quantization=awq")
    print()
    print("  关键：device_ids 确保不同实例使用不同的 GPU")
    print("  容器内看到的 GPU 编号从 0 开始（与 device_ids 无关）")
    print()


def demo_model_warmup():
    """
    模型预热与冷启动优化
    """
    print("=" * 60)
    print("模型预热与冷启动优化")
    print("=" * 60)
    print()
    print("冷启动问题：")
    print()
    print("  vLLM 启动后的首次请求特别慢：")
    print()
    print("  [容器启动] → [加载模型权重 30-60s] → [首次请求]")
    print("                                            ↓")
    print("                                    [编译 CUDA Graph 10-30s]")
    print("                                    [分配 KV Cache 内存]")
    print("                                    [首次推理完成]")
    print("                                            ↓")
    print("                                    [后续请求正常速度]")
    print()
    print("  首次请求延迟 = 正常延迟 + CUDA Graph 编译时间")
    print("  用户感知：第一个问题等很久，后面就正常了")
    print()
    print("解决方案：模型预热（Warmup）")
    print()
    print("  在 HEALTHCHECK 变 healthy 后，自动发送一个预热请求：")
    print()
    print("  ```python")
    print("  import requests")
    print()
    print("  def warmup_vllm(url='http://localhost:8000/v1/chat/completions', model='Qwen/Qwen2.5-7B-Instruct'):")
    print("      \"\"\"发送预热请求，触发 CUDA Graph 编译\"\"\"")
    print("      print('开始模型预热...')")
    print("      payload = {")
    print("          'model': model,")
    print("          'messages': [{'role': 'user', 'content': 'hi'}],")
    print("          'max_tokens': 1,")
    print("          'temperature': 0,")
    print("      }")
    print()
    print("      start = time.time()")
    print("      resp = requests.post(url, json=payload)")
    print("      warmup_time = time.time() - start")
    print()
    print("      if resp.status_code == 200:")
    print("          print(f'预热完成！耗时: {warmup_time:.2f}s')")
    print("      else:")
    print("          print(f'预热失败: {resp.status_code}')")
    print("  ```")
    print()
    print("  更优雅的方式：在 docker-compose 中用启动脚本：")
    print()
    print("  entrypoint: /app/startup.sh")
    print()
    print("  # startup.sh")
    print("  #!/bin/bash")
    print("  python -m vllm.entrypoints.openai.api_server \"$@\" &")
    print("  VLLM_PID=$!")
    print()
    print("  # 等待服务就绪")
    print("  until curl -sf http://localhost:8000/health; do sleep 2; done")
    print()
    print("  # 发送预热请求")
    print("  curl -s http://localhost:8000/v1/chat/completions \\")
    print("    -H 'Content-Type: application/json' \\")
    print("    -d '{\"model\":\"Qwen/Qwen2.5-7B-Instruct\",\"messages\":[{\"role\":\"user\",\"content\":\"hi\"}],\"max_tokens\":1}'")
    print()
    print("  wait $VLLM_PID")
    print()
    print("  这样容器 healthy 后，CUDA Graph 已编译，首次用户请求不会卡")
    print()


def demo_rate_limiting_strategy():
    """
    三层限流策略
    """
    print("=" * 60)
    print("三层限流策略")
    print("=" * 60)
    print()
    print("LLM 服务的限流比普通 API 更复杂，因为：")
    print("  - 请求耗时长（秒级 vs 毫秒级）")
    print("  - GPU 显存是硬约束，不是 CPU 那样能超售")
    print("  - 并发过高 → KV Cache 溢出 → 抢占 → 所有用户都慢")
    print()
    print("┌─────────────────────────────────────────────────────┐")
    print("│  第一层：Nginx 限流（请求级）                         │")
    print("├─────────────────────────────────────────────────────┤")
    print("│  limit_req_zone $binary_remote_addr zone=api:10m   │")
    print("│      rate=10r/s;                                     │")
    print("│  limit_req zone=api burst=20 nodelay;               │")
    print("│                                                      │")
    print("│  控制：每 IP 每秒请求数                               │")
    print("│  效果：防止单个客户端发送过多请求                      │")
    print("│  限制：不知道每个请求的 token 数                      │")
    print("└─────────────────────────────────────────────────────┘")
    print()
    print("┌─────────────────────────────────────────────────────┐")
    print("│  第二层：vLLM 并发限制（GPU 级）                      │")
    print("├─────────────────────────────────────────────────────┤")
    print("│  --max-num-seqs 64                                   │")
    print("│  --gpu-memory-utilization 0.9                        │")
    print("│                                                      │")
    print("│  控制：同时处理的请求序列数                           │")
    print("│  效果：超过限制的请求排队等待                         │")
    print("│  限制：只控制并发数，不区分用户                       │")
    print("└─────────────────────────────────────────────────────┘")
    print()
    print("┌─────────────────────────────────────────────────────┐")
    print("│  第三层：应用层配额（用户级）                         │")
    print("├─────────────────────────────────────────────────────┤")
    print("│  自定义 API 网关或中间件：                            │")
    print("│  - 按 API Key 限流：每用户每分钟 N 个请求             │")
    print("│  - 按 token 用量限流：每用户每天 M 个 token           │")
    print("│  - 优先级队列：付费用户优先，免费用户排队             │")
    print("│                                                      │")
    print("│  实现方式：                                          │")
    print("│  - FastAPI 中间件 + Redis 计数                        │")
    print("│  - 专用 API 网关（Kong, Traefik）                    │")
    print("│  - vLLM 的 --api-key 参数做基本认证                   │")
    print("└─────────────────────────────────────────────────────┘")
    print()
    print("推荐组合：")
    print("  免费服务：Nginx 5r/s + vLLM max-num-seqs=32 + 按用户 100req/day")
    print("  付费服务：Nginx 50r/s + vLLM max-num-seqs=128 + 无限制")
    print("  内部服务：Nginx 200r/s + vLLM max-num-seqs=256 + 无限制")
    print()


def explain_rolling_update():
    """
    滚动更新与零停机
    """
    print("=" * 60)
    print("滚动更新与零停机部署")
    print("=" * 60)
    print()
    print("场景：vLLM 版本升级（如 v0.19.0 → v0.20.0）")
    print()
    print("❌ 直接更新（有停机时间）：")
    print("  docker compose down     # 所有服务停止")
    print("  docker compose up -d    # 所有服务重启")
    print("  → 停机时间 = 模型加载时间（30-90s）")
    print()
    print("✓ 滚动更新（零停机）：")
    print()
    print("  前提：至少 2 个 vLLM 实例 + Nginx 负载均衡")
    print()
    print("  步骤：")
    print("  1. 更新 vllm-1 镜像")
    print("     docker compose up -d --no-deps vllm-1")
    print("     → vllm-1 停止 → 加载模型 → 健康检查通过")
    print("     → 期间 vllm-2 继续服务（Nginx 只转发到 vllm-2）")
    print()
    print("  2. 等待 vllm-1 healthy")
    print("     docker compose ps  # 确认 vllm-1 状态为 healthy")
    print()
    print("  3. 更新 vllm-2 镜像")
    print("     docker compose up -d --no-deps vllm-2")
    print("     → vllm-2 停止 → 加载模型 → 健康检查通过")
    print("     → 期间 vllm-1 已在服务")
    print()
    print("  4. 两个实例都已更新，零停机完成")
    print()
    print("  关键：Nginx 的 health_check 或 passive check")
    print("  当某个后端不可用时，Nginx 自动排除，不转发请求")
    print()
    print("docker-compose 中的滚动更新配置：")
    print()
    print("  deploy:")
    print("    update_config:")
    print("      parallelism: 1        # 每次更新 1 个实例")
    print("      delay: 120s           # 更新间隔（等模型加载）")
    print("      order: start-first    # 先启新的再停旧的")
    print("    healthcheck:")
    print("      ...")
    print()
    print("注意：GPU 部署的滚动更新受 GPU 数量限制")
    print("  - 4 张 GPU，2 实例各用 2 张 → 无法同时运行 3 个实例")
    print("  - 滚动更新时需要先停旧实例，再启新实例")
    print("  - 停机时间 = 模型加载时间（不可避免的短暂中断）")
    print()


def explain_security_hardening():
    """
    生产环境安全加固
    """
    print("=" * 60)
    print("生产环境安全加固")
    print("=" * 60)
    print()
    print("1. 容器安全")
    print()
    print("   # 使用非 root 用户运行")
    print("   USER nobody")
    print()
    print("   # 只读文件系统（只保留可写目录）")
    print("   read_only: true")
    print("   tmpfs:")
    print("     - /tmp")
    print("     - /root/.cache")
    print()
    print("   # 禁止特权升级")
    print("   security_opt:")
    print("     - no-new-privileges:true")
    print()
    print("2. 网络安全")
    print()
    print("   # vLLM 不直接暴露到宿主机")
    print("   # 只通过 Nginx 反向代理访问")
    print("   vllm:")
    print("     ports: []               # 不映射端口到宿主机")
    print("     networks:")
    print("       - llm-deploy-net      # 只在内网可达")
    print()
    print("   # Nginx 是唯一对外暴露的服务")
    print("   nginx:")
    print("     ports:")
    print("       - '80:80'")
    print()
    print("   # 限制 /metrics 端点的访问")
    print("   location /metrics {")
    print("       allow 172.16.0.0/12;  # 只允许内网")
    print("       deny all;")
    print("       proxy_pass http://vllm_backend;")
    print("   }")
    print()
    print("3. 认证与密钥")
    print()
    print("   # vLLM 内置 API Key 认证")
    print("   vllm:")
    print("     command:")
    print("       - --api-key=your-secret-key")
    print()
    print("   # 客户端请求时带上 key")
    print("   curl -H 'Authorization: Bearer your-secret-key' ...")
    print()
    print("   # ⚠️ 不要在 docker-compose.yml 中硬编码密钥")
    print("   # 使用环境变量或 Docker secrets：")
    print("   vllm:")
    print("     environment:")
    print("       - VLLM_API_KEY=${VLLM_API_KEY}  # 从 .env 读取")
    print()
    print("4. HTTPS")
    print()
    print("   # Nginx SSL 终止")
    print("   server {")
    print("       listen 443 ssl;")
    print("       ssl_certificate /etc/nginx/ssl/cert.pem;")
    print("       ssl_certificate_key /etc/nginx/ssl/key.pem;")
    print("   }")
    print()
    print("5. 安全检查清单")
    print()
    print("   □ vLLM 端口不直接暴露到公网")
    print("   □ Nginx 配置限流和超时")
    print("   □ API Key 认证启用")
    print("   □ 密钥不硬编码，使用环境变量")
    print("   □ /metrics 端点限制内网访问")
    print("   □ 容器使用非 root 用户")
    print("   □ HTTPS 启用（生产环境必须）")
    print("   □ 定期更新基础镜像（安全补丁）")
    print("   □ Docker 日志配置日志轮转（避免磁盘满）")
    print()


if __name__ == "__main__":
    print("大模型部署学习 - Stage 5: 高级部署策略")
    print()

    # 1. 多实例部署
    explain_multi_instance()

    # 2. 模型预热
    demo_model_warmup()

    # 3. 限流策略
    demo_rate_limiting_strategy()

    # 4. 滚动更新
    explain_rolling_update()

    # 5. 安全加固
    explain_security_hardening()

    print("=" * 60)
    print("Stage 5 高级部署要点总结")
    print("=" * 60)
    print("1. 多实例部署：同模型提升吞吐，异构模型按需路由")
    print("2. GPU 绑定：device_ids 确保实例间不争抢 GPU")
    print("3. 模型预热：启动后发送 warmup 请求消除冷启动延迟")
    print("4. 三层限流：Nginx(请求级) + vLLM(并发级) + 应用(用户级)")
    print("5. 滚动更新：多实例 + Nginx 实现接近零停机")
    print("6. 安全加固：非 root、网络隔离、密钥管理、HTTPS")
